# ASP.NET Core
- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectedServiceName: 'Free Trial (cf964586-8280-4bc5-a71f-fe1545601cd9)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'sreetestdotnet-rg'
    location: 'South Central US'
    csmFile: '$(System.DefaultWorkingDirectory)/**/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/**/parameters.json'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'